name: Pylint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        #, "3.9", "3.10", "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          echo done installations
        # which pylint
      - name: Analysing the code with pylint
        run: |
          git remote set-branches --add origin main
          git fetch origin
          echo commented pylint for now
          #pylint --rcfile=.pylintrc $(git ls-files '*.py')
          #$(git diff --name-only HEAD ${{ github.base_ref }})
      - name: now running tests for code base
        run: |
          echo copy SECRETCONFIG from github to a file...
          echo "${{ secrets.SECRETCONFIG }}" > secrets.config
          echo running the test
          python AI-InvestiBot/implementation.py
          echo test completed!!!
